[supabase]
url = "https://arwacdkbojjfelqcqank.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyd2FjZGtib2pqZmVscWNxYW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzMTQzNjksImV4cCI6MjEwMTg5MDM2OX0.bpuXEYsyqODOVQLpOE4CPBIWWyi8ZJdqibsYj7wNPDU"

# Si en el futuro añades los datos de SAP, los añadirás así (sin repetir [supabase]):
[sap_s4hana]
token_url = "https://tu-instancia.authentication.sap.com/oauth/token"
client_id = "tu_id"
client_secret = "tu_secret"
service_root_url = "https://tu-instancia.s4hana.ondemand.com/sap/opu/odata/sap/"